<a href="https://colab.research.google.com/github/muyeblog/implementAlgorithmFromScratch/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 参看：https://blog.csdn.net/hgnuxc_1993/article/details/114680399

In [ ]:
from sklearn.linear_model import LogisticRegression
from math import * # 含 exp
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from numpy import *
import numpy as np

In [ ]:
class LogisticRegressionClassifier(object):
  def __init__(self,eta=0.1,loop=30):
    self.eta = eta
    self.loop=loop
  
  def sigmoid(self,x):
    return 1.0 / (1 + exp(-x))
  
  def data_tranforce(self,x_train):
    data = []
    d = []
    for x in x_train: # x 为数组类型
      data.append([1.0,*x])  # 将每一行数组增加一个 1.0 的值，对应参数 b，*x 是去掉[]符号,形成一行数值
      # c = list(x)  # 将一维数组变成列表
      # c.insert(0,1.0) # 这种insert()方法必须是列表
      # print(list(x).insert(0,1.0))
      # d.append(c) # 类似 d = [[1.0,2,3],[1.0,3,4.8]]
    return data
  
  def fit(self,x_train,y_train):
    data_mat = self.data_tranforce(x_train) # 处理每个样本的特征值
    n = shape(data_mat)[1]  # 求出 data_mat对应参数的个数
    self.weight=ones((n,1)) # 初始化参数w数组
    cls = self.loop
    for k in range(cls): # 循环 次数
      for i in range(len(x_train)): # 遍历每一个样本
        h = self.sigmoid(np.dot(data_mat[i],self.weight))  # np.dot矩阵相乘
        err = (y_train[i] - h)
        # 随着每次更新err 下面就会更新self.weight 的向量
        ## 这里是一次性更新了一个样本在每个特征维度上的weight
        self.weight += self.eta*err*np.transpose([data_mat[i]]) # 一维数组转置必须加一个[]

  def test(self,x_test,y_test):
    numbers=0
    x_test = self.data_tranforce(x_test)  # 处理每个样本的特征值加一个 1.0
    for x,y in zip(x_test,y_test):
      result = np.dot(x,self.weight)
      if(result >0 and y==1) or (result < 0 and y==0):
        numbers += 1
    return float(numbers)/float(len(x_test))


In [ ]:
def main():
    load=load_iris()
    x=load.data[:100,:2]
    y=load.target[:100]
    y=np.where(y==1,1,0)
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
    my_l=LogisticRegressionClassifier()
    my_l.fit(x_train,y_train)
    print("准确率：",my_l.test(x_test,y_test))
 
if __name__== "__main__":
    main()

# ————————————————
# 版权声明：本文为CSDN博主「无尽的沉默」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
# 原文链接：https://blog.csdn.net/hgnuxc_1993/article/details/114680399

准确率： 1.0


In [ ]:
load = load_iris()

In [ ]:
len(load.data)

150

In [ ]:
load.data.shape

(150, 4)

In [ ]:
load.data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [ ]:
load.target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
x = load.data[:100]
y = load.target[:100]

In [ ]:
data=[]
for x in load.data[:100]:
  # print(*x)  # * 去掉 []
  data.append([1.0,*x])
  # print(data)
print(shape(data)) # (sample_size,field_size)

(100, 5)


In [ ]:
y=load.target[:10]

In [ ]:
y[2]

0

In [ ]:
np.where(load.target[:100]==1,1,0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
data[2]

[1.0, 4.7, 3.2, 1.3, 0.2]

In [ ]:
shape(data)[1]

5

In [ ]:
n=shape(data)[1]

In [ ]:
def sigmoid(x):
  return 1.0 / (1 + exp(-x))

In [ ]:
loop=30
eta=0.1
weight=ones((n,1)) # 初始化参数w数组
cls = loop

In [ ]:
weight

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
data[0]

[1.0, 5.1, 3.5, 1.4, 0.2]

In [ ]:
sigmoid(np.dot(data[0],weight))

array([0.99998633])

In [ ]:
h = sigmoid(np.dot(data[0],weight))

In [ ]:
err = (y[0] - h)

In [ ]:
err

array([-0.99998633])

In [ ]:
h = sigmoid(np.dot(data[1],weight))

In [ ]:
err = (y[1] - h)

In [ ]:
err

array([-0.99997246])

In [ ]:
np.transpose([data[0]])

array([[1. ],
       [5.1],
       [3.5],
       [1.4],
       [0.2]])

In [ ]:
del err

for k in range(cls): # 循环 次数
  for i in range(len(x)): # 遍历每一个样本
    print(i)
    h = sigmoid(np.dot(data[i],weight))
    err = (y[i] - h)
    print(eta)
    print('error')
    print(err)
      # 随着每次更新err 下面就会更新self.weight 的向量
    print(np.transpose([data[i]]))
    print(eta*err)
    print(weight)
    ## 这里是一次性更新了一个样本在每个特征维度上的weight
    weight += eta*err*np.transpose([data[i]]) # 变成 1*4的数组，一维数组转置必须加一个[] ?
    print('weight')
    print(weight)
    break
  break

0
0.1
error
[-0.00372003]
[[1. ]
 [5.1]
 [3.5]
 [1.4]
 [0.2]]
[-0.000372]
[[ 0.59306113]
 [-1.07538825]
 [-0.42428605]
 [ 0.43028558]
 [ 0.91861223]]
weight
[[ 0.59268913]
 [-1.07728546]
 [-0.42558806]
 [ 0.42976478]
 [ 0.91853783]]


In [ ]:
print(err.shape)

(1,)


In [ ]:
print(np.transpose([data[0]]).shape)

(5, 1)


In [ ]:
eta*err

array([-0.00037783])

In [ ]:
array([-0.00037783])*np.transpose(data[0])*data[0]

array([-3.7783000e-04, -9.8273583e-03, -4.6284175e-03, -7.4054680e-04,
       -1.5113200e-05])

In [ ]:
eta*err*np.transpose([data[0]])

array([[-3.72002530e-04],
       [-1.89721290e-03],
       [-1.30200885e-03],
       [-5.20803542e-04],
       [-7.44005060e-05]])

In [ ]:
data[0]

[1.0, 5.1, 3.5, 1.4, 0.2]

In [ ]:
data[0]*eta*err*np.transpose([data[0]])

TypeError: ignored

In [ ]:
## np.dot demo
m = np.array([[1, 2, 3], [4, 5, 6]])       ##2X3 矩阵
n = np.array([[1, 2], [3, 4], [5, 6]])     ##3X2 矩阵
np.dot(m,n) # 矩阵相乘

array([[22, 28],
       [49, 64]])

In [ ]:
np.matmul(m, n)

array([[22, 28],
       [49, 64]])

In [ ]:
# m*n # 报错 ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 
# n*m # 报错 operands could not be broadcast together with shapes (3,2) (2,3) 

In [ ]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
n

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.array([[1,3,5], [2, 4,6]]).shape

(2, 3)

In [ ]:
n1 = np.array([[1], [3], [5]]) 
np.dot(m,n1)

array([[22],
       [49]])

In [ ]:
np.matmul(m, n)

In [ ]:
x = np.array([[1,3], [2,4]])          #2X2
print(x.shape)
y = np.array([[[1, 1], [2, 4]]])  #1X2X2
x * y 

(2, 2)


array([[[ 1,  3],
        [ 4, 16]]])

In [ ]:
x = np.array([[1], [2]])          #2X1
y = np.array([[[1, 1], [2, 4]]])  #1X2X2
x * y 

array([[[1, 1],
        [4, 8]]])