<a href="https://colab.research.google.com/github/muyeblog/implementAlgorithmFromScratch/blob/main/LogisticRegression_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from math import * # 含 exp
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from numpy import *
import numpy as np

In [ ]:
class LogisticRegressionClassifier_v2(object):
  def __init__(self,eta=0.1,loop=30):
    self.eta=eta
    self.loop=loop
  
  def sigmoid(self,x):
    return 1.0/(1+exp(-x))
  
  def data_tranforce(self,x_train):
    data = []
    d = []
    for x in x_train:
      data.append([1.0,*x])
    return np.array(data)
  
  def fit(self,x_train,y_train):
    data_mat = self.data_tranforce(x_train)
    n = shape(data_mat)[1]
    m = shape(data_mat)[0]
    self.weight = ones((n,1))
    cls = self.loop
    h_list = []
    for i in range(len(x_train)):
      h = self.sigmoid(np.dot(data_mat[i],self.weight))
      h_list.append(h)
    h_mat = np.array(h_list)
    # print(h_mat.shape)
    h_mat = h_mat.reshape(m,)
    # print(h_mat.shape)
    # print(y_train.shape)
    err = y_train - h_mat
    print(err)
    print(err.shape)
    print(shape(data_mat.transpose()))
    err = err.reshape(m,1)
    print(err)
    print(self.weight.shape)
    print(self.eta*np.dot(data_mat.transpose(),err))
    self.weight += self.eta*np.dot(data_mat.transpose(),err) # 两个数组进行矩阵乘法计算使用np.dot
  
  def test(self,x_test,y_test):
    numbers=0
    x_test = self.data_tranforce(x_test)  # 处理每个样本的特征值加一个 1.0
    for x,y in zip(x_test,y_test):
      result = np.dot(x,self.weight)
      if(result >0 and y==1) or (result < 0 and y==0):
        numbers += 1
    return float(numbers)/float(len(x_test))


In [ ]:
def main():
    load=load_iris()
    x=load.data[:100,:2]
    y=load.target[:100]
    y=np.where(y==1,1,0)
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
    my_l=LogisticRegressionClassifier_v2()
    my_l.fit(x_train,y_train)
    print("准确率：",my_l.test(x_test,y_test))
 
if __name__== "__main__":
    main()

[-9.99932276e-01  6.77241496e-05  2.48455082e-04 -9.99932276e-01
  1.23394576e-04  2.75356911e-05  1.36370327e-04  7.48462275e-05
  9.14158739e-05  6.77241496e-05  1.36370327e-04  5.01721647e-05
 -9.99979601e-01  5.01721647e-05 -9.99898971e-01 -9.99925154e-01
 -9.99917283e-01  5.01721647e-05  5.54485247e-05 -9.99849290e-01
 -9.99876605e-01  3.36319640e-05  5.01721647e-05 -9.99966368e-01
  3.04315569e-05  2.03990873e-05 -9.99917283e-01  2.49153889e-05
 -9.99898971e-01  4.10778678e-05  1.01029194e-04  3.35350130e-04
 -9.99751545e-01  1.84071905e-04  4.10778678e-05  7.48462275e-05
 -9.99954602e-01 -9.99972464e-01 -9.99949828e-01  4.53978687e-05
 -9.99908584e-01 -9.99849290e-01 -9.99944551e-01  6.12797396e-05
 -9.99932276e-01 -9.99833442e-01 -9.99925154e-01  1.67014218e-05
  2.49153889e-05  1.11653341e-04 -9.99949828e-01  4.10778678e-05
 -9.99958922e-01 -9.99876605e-01  1.50710358e-04 -9.99944551e-01
 -9.99917283e-01 -9.99925154e-01  6.77241496e-05 -9.99751545e-01
 -9.99966368e-01  7.48462

In [ ]:
# 2-D array: 2 x 3
two_dim_matrix_one = np.array([[1, 2, 3], [4, 5, 6]])
# 2-D array: 3 x 2
two_dim_matrix_two = np.array([[1, 2], [3, 4], [5, 6]])

two_multi_res = np.dot(two_dim_matrix_one, two_dim_matrix_two)
print('two_multi_res: %s' %(two_multi_res))
# ————————————————
# 版权声明：本文为CSDN博主「cltdevelop」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
# 原文链接：https://blog.csdn.net/u012609509/article/details/70230204

two_multi_res: [[22 28]
 [49 64]]


In [ ]:
# 2-D array: 2 x 3
two_dim_matrix_one = np.mat([[1, 2, 3], [4, 5, 6]])
# 2-D array: 3 x 2
two_dim_matrix_two = np.mat([[1, 2], [3, 4], [5, 6]])


In [ ]:
two_dim_matrix_one

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
two_dim_matrix_two

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:

two_multi_res = np.dot(two_dim_matrix_one, two_dim_matrix_two)
print('two_multi_res: %s' %(two_multi_res))
print('two_dim_matrix_one*two_dim_matrix_two: %s' % (two_dim_matrix_one*two_dim_matrix_two))
# ————————————————
# 版权声明：本文为CSDN博主「cltdevelop」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
# 原文链接：https://blog.csdn.net/u012609509/article/details/70230204

two_multi_res: [[22 28]
 [49 64]]
two_dim_matrix_one*two_dim_matrix_two: [[22 28]
 [49 64]]


In [ ]:
two_dim_matrix_one*two_dim_matrix_two

matrix([[22, 28],
        [49, 64]])

In [ ]:
## 矩阵乘法
two_dim_matrix_one = np.array([[1, 2, 3], [4, 5, 6]])
another_two_dim_matrix_one = np.array([[7, 8, 9], [4, 7, 1]])

In [ ]:
two_dim_matrix_one

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
another_two_dim_matrix_one

array([[7, 8, 9],
       [4, 7, 1]])

In [ ]:
# 对应元素相乘 element-wise product
element_wise = two_dim_matrix_one * another_two_dim_matrix_one
print('element wise product: %s' %(element_wise))
# ————————————————
# 版权声明：本文为CSDN博主「cltdevelop」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
# 原文链接：https://blog.csdn.net/u012609509/article/details/70230204

element wise product: [[ 7 16 27]
 [16 35  6]]
